--This is a knife for Posted Admin.
--I(PostA_Note), edited this so theres no warnings or prints in the Output.
--Thats basically all.
--I don't know the original owner/dev or this knife...

--                                                                                                            dddddddd
--PPPPPPPPPPPPPPPPP                                             tttt                                          d::::::d
--P::::::::::::::::P                                         ttt:::t                                          d::::::d
--P::::::PPPPPP:::::P                                        t:::::t                                          d::::::d
--PP:::::P     P:::::P                                       t:::::t                                          d:::::d 
--  P::::P     P:::::P  ooooooooooo       ssssssssss   ttttttt:::::ttttttt        eeeeeeeeeeee        ddddddddd:::::d 
--  P::::P     P:::::Poo:::::::::::oo   ss::::::::::s  t:::::::::::::::::t      ee::::::::::::ee    dd::::::::::::::d 
--  P::::PPPPPP:::::Po:::::::::::::::oss:::::::::::::s t:::::::::::::::::t     e::::::eeeee:::::ee d::::::::::::::::d 
--  P:::::::::::::PP o:::::ooooo:::::os::::::ssss:::::stttttt:::::::tttttt    e::::::e     e:::::ed:::::::ddddd:::::d 
--  P::::PPPPPPPPP   o::::o     o::::o s:::::s  ssssss       t:::::t          e:::::::eeeee::::::ed::::::d    d:::::d 
--  P::::P           o::::o     o::::o   s::::::s            t:::::t          e:::::::::::::::::e d:::::d     d:::::d 
--  P::::P           o::::o     o::::o      s::::::s         t:::::t          e::::::eeeeeeeeeee  d:::::d     d:::::d 
--  P::::P           o::::o     o::::ossssss   s:::::s       t:::::t    tttttte:::::::e           d:::::d     d:::::d 
--PP::::::PP         o:::::ooooo:::::os:::::ssss::::::s      t::::::tttt:::::te::::::::e          d::::::ddddd::::::dd
--P::::::::P         o:::::::::::::::os::::::::::::::s       tt::::::::::::::t e::::::::eeeeeeee   d:::::::::::::::::d
--P::::::::P          oo:::::::::::oo  s:::::::::::ss          tt:::::::::::tt  ee:::::::::::::e    d:::::::::ddd::::d
--PPPPPPPPPP            ooooooooooo     sssssssssss              ttttttttttt      eeeeeeeeeeeeee     ddddddddd   ddddd
--
--                                                        dddddddd                                                 
--                             AAA                        d::::::d                          iiii                   
--                            A:::A                       d::::::d                         i::::i                  
--                           A:::::A                      d::::::d                          iiii                   
--                          A:::::::A                     d:::::d                                                  
--                         A:::::::::A            ddddddddd:::::d    mmmmmmm    mmmmmmm   iiiiiiinnnn  nnnnnnnn    
--                        A:::::A:::::A         dd::::::::::::::d  mm:::::::m  m:::::::mm i:::::in:::nn::::::::nn  
--                       A:::::A A:::::A       d::::::::::::::::d m::::::::::mm::::::::::m i::::in::::::::::::::nn 
--                      A:::::A   A:::::A     d:::::::ddddd:::::d m::::::::::::::::::::::m i::::inn:::::::::::::::n
--                     A:::::A     A:::::A    d::::::d    d:::::d m:::::mmm::::::mmm:::::m i::::i  n:::::nnnn:::::n
--                    A:::::AAAAAAAAA:::::A   d:::::d     d:::::d m::::m   m::::m   m::::m i::::i  n::::n    n::::n
--                   A:::::::::::::::::::::A  d:::::d     d:::::d m::::m   m::::m   m::::m i::::i  n::::n    n::::n
--                  A:::::AAAAAAAAAAAAA:::::A d:::::d     d:::::d m::::m   m::::m   m::::m i::::i  n::::n    n::::n
--                 A:::::A             A:::::Ad::::::ddddd::::::ddm::::m   m::::m   m::::mi::::::i n::::n    n::::n
--                A:::::A               A:::::Ad:::::::::::::::::dm::::m   m::::m   m::::mi::::::i n::::n    n::::n
--               A:::::A                 A:::::Ad:::::::::ddd::::dm::::m   m::::m   m::::mi::::::i n::::n    n::::n
--              AAAAAAA                   AAAAAAAddddddddd   dddddmmmmmm   mmmmmm   mmmmmmiiiiiiii nnnnnn    nnnnnn